# mypy: ignore-errors
# ruff: noqa

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import warnings

import grpc
import ordenes_pb2 as ordenes__pb2

GRPC_GENERATED_VERSION = "1.83.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in ordenes_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class GestorOrdenesStub:
    """1. El Servicio (Las funciones disponibles)"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CrearOrden = channel.unary_unary(
            "/ordenes.GestorOrdenes/CrearOrden",
            request_serializer=ordenes__pb2.OrdenRequest.SerializeToString,
            response_deserializer=ordenes__pb2.OrdenResponse.FromString,
            _registered_method=True,
        )


class GestorOrdenesServicer:
    """1. El Servicio (Las funciones disponibles)"""

    def CrearOrden(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_GestorOrdenesServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "CrearOrden": grpc.unary_unary_rpc_method_handler(
            servicer.CrearOrden,
            request_deserializer=ordenes__pb2.OrdenRequest.FromString,
            response_serializer=ordenes__pb2.OrdenResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "ordenes.GestorOrdenes", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("ordenes.GestorOrdenes", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class GestorOrdenes:
    """1. El Servicio (Las funciones disponibles)"""

    @staticmethod
    def CrearOrden(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ordenes.GestorOrdenes/CrearOrden",
            ordenes__pb2.OrdenRequest.SerializeToString,
            ordenes__pb2.OrdenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
