# mypy: ignore-errors
# ruff: noqa

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ordenes.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 7, 35, 1, "", "ordenes.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rordenes.proto\x12\x07ordenes"/\n\x0cOrdenRequest\x12\x10\n\x08producto\x18\x01 \x01(\t\x12\r\n\x05monto\x18\x02 \x01(\x02",\n\rOrdenResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07mensaje\x18\x02 \x01(\t2N\n\rGestorOrdenes\x12=\n\nCrearOrden\x12\x15.ordenes.OrdenRequest\x1a\x16.ordenes.OrdenResponse"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "ordenes_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_ORDENREQUEST"]._serialized_start = 26
    _globals["_ORDENREQUEST"]._serialized_end = 73
    _globals["_ORDENRESPONSE"]._serialized_start = 75
    _globals["_ORDENRESPONSE"]._serialized_end = 119
    _globals["_GESTORORDENES"]._serialized_start = 121
    _globals["_GESTORORDENES"]._serialized_end = 199
# @@protoc_insertion_point(module_scope)
